# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20170407_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default=b'', max_length=50, verbose_name='\u8bfe\u7a0b\u6807\u7b7e'),
        ),
    ]
