# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170410_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='brithday',
            new_name='birthday',
        ),
    ]
