# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170405_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=b'', upload_to=b'teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
